# Exported from Render on 2024-03-22T01:21:15Z
databases:
- name: smiley-db
  databaseName: smiley
  user: smileydev
  plan: free
  region: ohio
  ipAllowList:
  - source: 0.0.0.0/0
    description: everywhere
  postgresMajorVersion: "16"
version: "1"